/**
 * Copyright (c) 2017-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
 

/*
 module.exports = {
  mySidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // generate sidebar slice from the docs folder (or versioned_docs/<version>)
    },
  ],
};
*/
///*
module.exports = {
  someSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'about-legal-tech-class',
      ],
    },
    {
      type: 'category',
      label: 'Legal Technology Overview',
      items: ['legal-tech-overview/legal-tech-overview',
              'legal-tech-overview/substantive-vs-non-substantive',
              'legal-tech-overview/maturity-model'],
    },
    {
      type: 'category',
      label: 'The Access to Justice Problem',
      items: [
        'a2j/a2j',
        'a2j/a2j-approaches',
        'a2j/a2j-technology',
      ],
    },       
    {
      type: 'category',
      label: 'Building Things',
      items: [
            'avoiding-failure/avoiding-failure',
          'interview-structure/building-an-app-outline',
          'choosing-project/choosing-project',
          'speaking-right-language/speaking-right-language',
    
        ]
    },
    {
      type: 'category',
      label: 'Testing',
      items: ['testing/testing',
              'testing/testing-scenarios',
              'testing/lorem-ipsum']
    },    
    // {
    //   type: 'category',
    //   label: 'Representing Rules in Code',
    //   items: ['representing-rules/representing-rules']
    // },  
    {
      type: 'category',
      label: 'A Practical Guide to Docassemble Development',
      items: [
        'introduction-to-docassemble',
        'practical-guide-docassemble/practical-guide-docassemble',
        'classes/docacon-2020/hello-world',
        'classes/docacon-2020/logic',
        'classes/docacon-2020/working-with-docx',
        'practical-guide-docassemble/controlling-interview-order',
        'practical-guide-docassemble/basic-troubleshooting',
        {
          type: "category",
          label: "Docassemble syntax",
          items: [
            'yaml',
            'markdown',
            'mako',
            'python',
            'jinja2',
          ]
        },
        {
          type: "category",
          label: "Working with lists and objects",
          items: [
            'practical-guide-docassemble/object-oriented-programming',
            'repeated-information',
          ]
        },
        {
          type: "category",
          label: "Customizing Docassemble",
          items: [
            'practical-guide-docassemble/theming-docassemble',
          ]
        },
        {
          type: 'category',
          label: 'Administering Docassemble',
          items: [
            'practical-guide-docassemble/setup-server',
            'practical-guide-docassemble/run-docassemble-docker-vscode',
            //'practical-guide-docassemble/combining-interviews',
            'practical-guide-docassemble/installing-production-app',
            'practical-guide-docassemble/updates-and-maintenance',
          ],
        },    
      ]
    },      
    {
      type: 'category',
      label: 'Classes and tutorials',
      items: [
        'classes/class-overview',
        'classes/other-classes',
        'classes/resources',
        {
          type: 'category',
          label: 'Legal Tech for Small Firms',
          items: [
            {
              type: 'category',
              label: 'Fall 2020 (archived)',
              items: [
                'classes/small-firms/2020/legal-tech-small-firms',
                'classes/small-firms/2020/legal-tech-small-firms-syllabus',
                'classes/small-firms/2020/legal-tech-small-firms-assignments',
                'classes/small-firms/2020/legal-tech-small-firms-rubric'    
              ]
            },
            {
              type: 'category',
              label: 'Fall 2021 (archived)',
              items: [
                'classes/small-firms/2021/legal-tech-small-firms',
                'classes/small-firms/2021/legal-tech-small-firms-syllabus',
                'classes/small-firms/2021/legal-tech-small-firms-assignments',
                'classes/small-firms/2021/legal-tech-small-firms-rubric'    
              ]
            },
            'classes/small-firms/2022-legal-tech',
          ]
        },
        {
          type: 'category',
          label: 'Lawyering in the Age of Smart Machines',
          items: [
            {
              type: 'category',
              label: 'Spring 2020 (Archived)',
              items: ['classes/smart-machines/2020/2020-law-smart-machines',
                'classes/smart-machines/2020/law-smart-machines-final-project',
                'classes/smart-machines/2020/project-ideas',
                'classes/smart-machines/2020/2020-law-smart-machines-assignment-1',
                'classes/smart-machines/2020/2020-law-smart-machines-assignment-2',
                'classes/smart-machines/2020/assignment-branch-logic',
                'classes/smart-machines/2020/assignment-creating-document']
            },            
            {
              type: 'category',
              label: 'Spring 2021 (Archived)',
              items: [
                'classes/smart-machines/2021/2021-smart-machines',
                'classes/smart-machines/2021/smart-machines-syllabus',
                'classes/smart-machines/2021/2021-smart-machines-assignments',
                'classes/smart-machines/2021/smart-machines-rubric'      
              ]
            },
            'classes/smart-machines/2022-smart-machines',
          ]
        },
        {
          type: 'category',
          label: 'Assembly Line Project Teaching Tuesdays',
          items: [
            'classes/assembly-line/assembly-line-assignment-1',
            'classes/assembly-line/assembly-line-assignment-3'
          ]
        },
        {
          type: 'category',
          label: 'Docacon 2020',
          items: [
            'classes/docacon-2020/hello-world',
            'classes/docacon-2020/logic',
            'classes/docacon-2020/question-types',
            'classes/docacon-2020/customizing-appearance',
            'classes/docacon-2020/working-with-docx',
          ]
        },
        {
          type: 'category',
          label: 'Other tutorials',
          items: ['tutorials']
        },             
      ]
    },
    {
      type: 'category',
      label: 'Appendices',
      items: ['appendices/editing-docusaurus'],
    },

  ]
}

//*/